# BS"D
# assorted functions
# Bentzion Fishman


def is_parsha(parsha):
    parsha_list = ['Bereishis',
                   'Noach',
                   'Lech Lecha',
                   'Vayera',
                   'Chayei Sarah',
                   'Toldos',
                   'Vayeitzei',
                   'Vayishlach',
                   'Vayeishev',
                   'Miketz',
                   'Vayigash',
                   'Vayechi',
                   'Shemos',
                   'Vaera',
                   'Bo',
                   'Beshalach',
                   'Yisro',
                   'Mishpatim',
                   'Terumah',
                   'Tetzaveh',
                   'Ki Sisa',
                   'Vayakhel',
                   'Pekudei',
                   'Vayikra',
                   'Tzav',
                   'Shemini',
                   'Tazria',
                   'Metzorah',
                   'Acharei Mos',
                   'Kedoshim',
                   'Emor',
                   'Behar',
                   'Bechukosai',
                   'Bamidbar',
                   'Naso',
                   'Behaaloscha',
                   'Shlach',
                   'Korach',
                   'Chukas',
                   'Balak',
                   'Pinchas',
                   'Matos',
                   'Masei',
                   'Devarim',
                   'Vaeschanan',
                   'Eikev',
                   'Reeh',
                   'Shoftim',
                   'Ki Seitzei',
                   'Ki Savo',
                   'Netzavim',
                   'Vayeilech',
                   'Haazinu',
                   'Vzos Habracha',
                   ]
    if parsha.casefold() in map(str.casefold, parsha_list):
        return True
    else:
        return False
